config/routes.rb
Rails.application.routes.draw do

  root            to: 'pages#home',     as: :home

  get '/kode-etik'        => 'pages#kode_etik',       as: :kode_etik
  get '/code-of-conduct'  => 'pages#code_of_conduct', as: :code_of_conduct

  get '/cfp'      => 'pages#cfp',     as: :cfp
  get '/cfp/new'  => 'pages#new_cfp', as: :new_cfp

  get '/sponsor'  => 'pages#sponsor', as: :sponsor
  get '/ticket'   => 'pages#ticket',  as: :ticket

  get '/app'       => 'pages#apps',      as: :apps
  get '/get_there' => 'pages#get_there', as: :get_there

  get '/2017'       => 'pages_2017#home', as: :home_2017
  get '/2017/faces' => 'pages_2017#faces'

  get '/2015'       => 'pages_2015#home', as: :home_2015
# get '/2015/faces' => 'pages_2015#faces'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/pages2015_controller.rb
class Pages2015Controller < ApplicationController

  def home
  end

  def faces
  end

end

app/controllers/pages2017_controller.rb
class Pages2017Controller < ApplicationController

  def home
  end

  def faces
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end


  def kode_etik
  end

  def code_of_conduct
  end


  def cfp
  end

  def new_cfp
  end


  def ticket
  end

  def sponsor
  end


  def app
  end

  def get_there
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/2017/_all_speakers.html.slim
- content_for :title do
  | GeekCamp - Faces

section.section

  header.header Faces

  .faces

    .faces__item
      = image_tag "speakers/vina-melody--big.jpg", class: "faces__image", alt: "Vina"
      .faces__name Vina Melody

    .faces__item
      = image_tag "speakers/tito.jpg", class: "faces__image", alt: "Smile"
      .faces__name Tito Pandu Brahmanto

    .faces__item
      = image_tag "speakers/mohan-krishnan.jpg", class: "faces__image", alt: "Mohan"
      .faces__name Mohan Krishnan

    .faces__item
      = image_tag "speakers/jaka-wiradisuria--big.jpg", class: "faces__image", alt: "Jaka"
      .faces__name Jaka Wiradisuria

    .faces__item
      = image_tag "speakers/taufiq-muhammadi--big.jpg", class: "faces__image", alt: "Taufiq"
      .faces__name Taufiq Muhammadi

    .faces__item
      = image_tag "speakers/willix-halim.jpg", class: "faces__image", alt: "Willix"
      .faces__name Willix Halim

    .faces__item
      = image_tag "speakers/didik-wicaksono.jpg", class: "faces__image", alt: "Didik"
      .faces__name Didik Wicaksono

    .faces__item
      = image_tag "speakers/buyung_bahari.png", class: "faces__image", alt: "Buyung"
      .faces__name Buyung Bahari

    .faces__item
      = image_tag "speakers/freddy_munandar.png", class: "faces__image", alt: "Freddy"
      .faces__name Freddy Munandar

    .faces__item
      = image_tag "speakers/mike-mazur.jpg", class: "faces__image", alt: "Mike"
      .faces__name Mike Mazur

    .faces__item
      = image_tag "speakers/hengki-sihombing--big.png", class: "faces__image", alt: "Hengki"
      .faces__name Hengki Sihombing

    .faces__item
      = image_tag "speakers/agung-setiawan--big.png", class: "faces__image", alt: "Agung"
      .faces__name Agung Setiawan

    .faces__item
      = image_tag "speakers/michael-ong.jpg", class: "faces__image", alt: "Michael"
      .faces__name Michael Ong

    .faces__item
      = image_tag "speakers/andreas-hadimulyono--big.png", class: "faces__image", alt: "Andreas"
      .faces__name Andreas Hadimulyono

    .faces__item
      = image_tag "speakers/aneesh-chandra--big.png", class: "faces__image", alt: "Aneesh"
      .faces__name Aneesh Chandra PN

    .faces__item
      = image_tag "speakers/herdy-handoko--small.jpg", class: "faces__image", alt: "Herdy"
      .faces__name Herdy Handoko

    .faces__item
      = image_tag "speakers/audy-tanudjaja--big.jpg", class: "faces__image", alt: "Audy"
      .faces__name Audy Tanudjaja

    .faces__item
      = image_tag "speakers/ady-rahmat-ma--big.jpg", class: "faces__image", alt: "Ady"
      .faces__name Ady Rahmat MA

    .faces__item
      = image_tag "speakers/estu-fardani--big.jpg", class: "faces__image", alt: "Estu"
      .faces__name Estu Fardani

    .faces__item
      = image_tag "speakers/riza-fahmi--big.jpg", class: "faces__image", alt: "Riza"
      .faces__name Riza Fahmi

    .faces__item
      = image_tag "speakers/mufid-afif--big.jpg", class: "faces__image", alt: "Mufid"
      .faces__name Muhammad Mufid Afif

    .faces__item
      = image_tag "speakers/achmad-gozali.jpg", class: "faces__image", alt: "Gozali"
      .faces__name Achmad Gozali

    .faces__item
      = image_tag "speakers/irvan-fahlepi--big.jpg", class: "faces__image", alt: "Irvan"
      .faces__name Irvan Fahlepi

    .faces__item
      = image_tag "speakers/adrianus-yoza-aprilio--small.jpg", class: "faces__image", alt: "Yoza"
      .faces__name Adrianus Yoza Aprilio

    .faces__item
      = image_tag "speakers/jim-halkyard.jpg", class: "faces__image", alt: "Jim"
      .faces__name Jim Halkyard

    .faces__item
      = image_tag "speakers/ditesh-gathani--big.jpg", class: "faces__image", alt: "Ditesh"
      .faces__name Ditesh Gathani

    .faces__item
      = image_tag "speakers/simon-sturmer.jpg", class: "faces__image", alt: "Simon"
      .faces__name Simon Stürmer

    /.faces__item
    /  = image_tag "smile.png", class: "faces__image", alt: "Smile"
    /  .faces__name Afif Akbar Iskandar

    .faces__item
      = image_tag "speakers/ardian-franindo--big.jpg", class: "faces__image", alt: "Ardian"
      .faces__name Ardian Franindo

    .faces__item
      = image_tag "speakers/hadikusuma-wahab.jpg", class: "faces__image", alt: "Diku"
      .faces__name Hadikusuma Wahab

    .faces__item
      = image_tag "speakers/ifnu-bima-fatkhan.jpg", class: "faces__image", alt: "Ifnu"
      .faces__name Ifnu Bima Fatkhan

    .faces__item
      = image_tag "speakers/mochamad-fathoni.jpg", class: "faces__image", alt: "Mochamad"
      .faces__name Mochamad Fathoni

    .faces__item
      = image_tag "speakers/giovanni-sakti--big.jpg", class: "faces__image", alt: "Giovanni"
      .faces__name Giovanni Sakti

app/views/2017/_jumbotron.html.slim
.jumbotron

  .jumbotron__logo
    = image_tag 'geekcamp--small.png', class: 'jumbotron__logo_image', alt: 'GeekCamp'
    .jumbotron__headline.m--red Indonesia's Community Tech Conference

  .jumbotron__headline One Day Event&ensp;&middot;&ensp;32 Speakers&ensp;&middot;&ensp;2 Topic Areas: Technology &amp; Product Design

  .jumbotron__datetime
    | July 15th, 2017
    br
    | The Hall 8th Floor, Senayan City, Jakarta

  .jumbotron__bg

app/views/layouts/_favicon.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">

app/views/layouts/_footer.html.slim
.footer
  | &copy; Copyleft #{ Date.today.year } by GeekCamp | No Rights Reserved

app/views/layouts/_navigation.html.slim
.navigation

  .navigation__logo
    = link_to home_path do
      = image_tag 'geekcamp--small.png', alt: 'GeekCamp'

  ul.navigation__links
    li= link_to "Submit a Talk!", cfp_path, class: 'navigation__link'
    /li= link_to "Speakers", home_path(anchor: 'speakers'), class: 'navigation__link'
    /li= link_to "Schedule", home_path(anchor: 'schedule'), class: 'navigation__link'
    li= link_to "Become a Sponsor!", sponsor_path, class: 'navigation__link'
    /li= link_to "Location", get_there_path, class: 'navigation__link'

    /li= link_to "Get Tickets", ticket_path,                   class: 'navigation__link'
    /li= link_to "Get The App", apps_path,                     class: 'navigation__link'

app/views/layouts/_participate.html.slim
.i-participate

  .participate
    .participate__misc
      ul.participate__links
        li.participate__link
          = link_to "Talk!", new_cfp_path
        li.participate__link
          = link_to "Sponsor!", sponsor_path

    .participate__misc
      ul.participate__links
        li.participate__link
          = link_to "Kode Etik", kode_etik_path
        li.participate__link
          = link_to "Code of Conduct", code_of_conduct_path

    .participate__misc
      ul.participate__links
        li.participate__link
          = link_to "GeekCamp 2017", home_2017_path
        li.participate__link
          = link_to "GeekCamp 2015", home_2015_path

    /.participate__ticket
    /  header.participate__header Get your ticket!
    /  p.participate__desc Grab your conference passes today with a special discount for buying online.
    /  = link_to "Get Tickets", ticket_path, class: 'participate__button button', target: '_blank'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <link rel="canonical" href="http://www.geekcamp.id/" />
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= render 'layouts/favicon' %>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>

  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', '<%= ENV['GOOGLE_ANALYTICS_TRACKING_ID'] %>', 'auto');
    ga('send', 'pageview');
  </script>
</head>
<body>
  <%= render 'layouts/navigation' %>
  <%= yield %>
  <%= render 'layouts/participate' %>
  <%# <%= render 'layouts/footer' %>

  <script type="text/javascript">
    //     _  _                   _
    //   _| || |_                | |
    //  |_  __  _| __ _  ___  ___| | _____ __ _ _ __ ___  _ __
    //   _| || |_ / _` |/ _ \/ _ \ |/ / __/ _` | '_ ` _ \| '_ \
    //  |_  __  _| (_| |  __/  __/   < (_| (_| | | | | | | |_) |
    //    |_||_|  \__, |\___|\___|_|\_\___\__,_|_| |_| |_| .__/
    //             __/ |                                 | |
    //            |___/                                  |_|

    let name = "%c#geekcamp", plea = "%cSubmit a talk lah! `cd ./cfp/new`",
        c = "color: #4E9A06; background: #000000; padding: 0 1rem; text-align: center; font-family: monospace; font-size: 32px;";
    if(window.console) {
      window.console.log(name, c);
      window.console.log(plea, c);
    }
  </script>
</body>
</html>

app/views/pages/_about.html.slim
.about

  .container

    header.about__header
      span.m--white About
      span.m--red GeekCamp

    p.about__description
      |  GeekCamp.id aspires to follow in the footsteps of #{ link_to "Kamal's", "https://twitter.com/kamal" } #{ link_to "geeky legacy", "https://www.techinasia.com/geekcamp-singapore" }, while expanding to incorporate Indonesia's rich tradition of strong communities.
      |  Our goal is nurture Indonesia's tech community through communication, collaboration, and accessibility.
      |  We are trying to accomplish this by
      span(title="ambil cuti buat conference susah banget")  hosting the conference on a weekend
      |  encouraging speakers of
      span(title="kamu tidak perlu punya jabatan: /C.O/")  all levels of seniority
      |  and charging a fraction of
      span(title="75k jauh lebih murah dari yang harga baju, tas, makan, sewa tempat -- makasi Sponsor :-)")  other conference ticket prices.

    p.about__description If you have any suggestions as to how GeekCamp.id can better accomplish the aforementioned goals, please reach out to us: #{ mail_to 'contact@geekcamp.id', 'contact@geekcamp.id', subject: "I've got a suggestion!" }

app/views/pages/_jumbotron.html.slim
.jumbotron.m--smaller

  .jumbotron__logo
    = image_tag 'geekcamp--small.png', class: 'jumbotron__logo_image', alt: 'GeekCamp'
    .jumbotron__headline.m--red Indonesia's Community Tech Conference

  .jumbotron__headline One Day Event&ensp;&middot;&ensp;2 Topic Areas: Technology &amp; Product Design

  /.jumbotron__datetime
  /  | July 15th, 2017
  /  br
  /  | The Hall 8th Floor, Senayan City, Jakarta

  .jumbotron__bg

app/views/pages/_location.html.slim
section.section

  header.header Location

  #map style="width:100%; height: 400px;"

javascript:
      function initMap() {
        var uluru = {lat: -6.2276003, lng: 106.7973705 };
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 17,
          center: uluru,
          scrollwheel: false
        });

        var directionLink = "<a target='_BLANK' href='https://www.google.co.id/maps/place/Senayan+City+Mall/@-6.2276003,106.7953756,17z/data=!3m2!4b1!5s0x2e69f148610ee4a3:0xaa9043c369af5e35!4m5!3m4!1s0x2e69f1485e476a65:0x300c043104acc004!8m2!3d-6.2276003!4d106.7975643?hl=en'>Get direction</a>";
        var contentString = '<div id="content">'+
            '<div id="siteNotice">'+
            '</div>'+
            '<h1 id="firstHeading" class="firstHeading">Senayan City Mall</h1>'+
            '<div id="bodyContent">'+
            '<br><p>Jl. Asia Afrika No.Lot 19, Gelora, Tanah Abang, <br>Kota Jakarta Pusat, <br>Daerah Khusus Ibukota Jakarta 12190<br><br><b>'
            + directionLink + '</b></p>'+
            '</div>'+
            '</div>';

        var infowindow = new google.maps.InfoWindow({
          content: contentString
        });

        var marker = new google.maps.Marker({
          title: "Senayan City",
          position: uluru,
          map: map
        });

        infowindow.open(map, marker);
      }

| <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAnIBMuL0pzIXHWCCFuWo-wwJxKIRJqbCQ&callback=initMap"></script>

app/views/pages/apps.html.slim
- content_for :title do
  | Apps | GeekCamp.id

section.apps

  .apps__container
    .apps__top

      .apps__container-left
        .apps__container-left__wrapper
          .apps__text Let's discover GeekCamp Indonesia Apps
          .apps__subtext Full conference agenda including presenters, schedule, map, exhibitors and more. Bookmark the talks that interest you most and view your personal schedule.
          .apps__logo
            a href="https://itunes.apple.com/app/id1256595392"
              = image_tag "ios-flat.png", class: "apps__logo-store"
            a href="https://play.google.com/store/apps/details?id=com.geekcamp.kodefox"
              = image_tag "google-flat.png", class: "apps__logo-store"

      .apps__container-right
        .apps__phone-container

app/views/pages/cfp.html.slim
- content_for :title do
  | Talk! | GeekCamp.id

= render 'jumbotron'

section.cfp__section
  header.header.m--full
    | Requirements
  ul.cfp__list
    li Paper and actual talk must be in English or Bahasa Indonesia.
    li Paper must have a title and an abstract of around 100 words.
    li Main stage talks are 20 minutes long, including Q&A.
    li Lightning talks are 10 minutes long, including Q&A.
    li Paper contents must adhere to our Code of Conduct.

section.cfp__section
  header.header.m--full
    | Submission Policy
  ul.cfp__list
    li All talks will be recorded and made available online at Vidio.com, free of charge, after the conference.
    li We accept talks that have been given before at other conferences.
    li You can submit any number of times.
    li You will retain copyright to your talk and any supporting materials.

section.cfp__section
  header.header.m--full
    | Review &amp; Selection Process
  ul.cfp__list
    li Reviews are double blind. We take into account novelty, depth, practical impact, and presentation.
    li Final selection is done by the organizing committee.

section.cfp__section
  header.header.m--full
    | Reimbursement
  ul.cfp__list
    li Selected speakers will receive free admission to the conference.
    li We will reserve one ticket at super early bird price for speakers who aren't selected.

section.cfp__section.m--center
  = link_to 'Submit Your Talk!', new_cfp_path, class: 'button'

app/views/pages/code_of_conduct.html.slim
section.code-of-conduct

  header.header Code of Conduct

  p All attendees, speakers, sponsors and volunteers at our conference are required to agree with the following code of conduct. Organizers will enforce this code throughout the event. We are expecting cooperation from all participants to help ensuring a safe environment for everybody.

section.code-of-conduct

  header.header.m--small The Quick Version:

  p Our conference is dedicated to providing a harassment-free conference experience for everyone, regardless of gender, gender identity and expression, age, sexual orientation, disability, physical appearance, body size, race, ethnicity, religion (or lack thereof), or technology choices. We do not tolerate harassment of conference participants in any form. Sexual language and imagery is not appropriate for any conference venue, including talks, workshops, parties, Twitter and other online media. Conference participants violating these rules may be sanctioned or expelled from the conference <strong>without a refund</strong> at the discretion of the conference organisers.

section.code-of-conduct

  header.header.m--small The Less Quick Version

  p Harassment includes offensive verbal comments related to gender, gender identity and expression, age, sexual orientation, disability, physical appearance, body size, race, ethnicity, religion, technology choices, sexual images in public spaces, deliberate intimidation, stalking, following, harassing photography or recording, sustained disruption of talks or other events, inappropriate physical contact, and unwelcome sexual attention.

  p Participants asked to stop any harassing behavior are expected to comply immediately.

  p Sponsors are also subject to the anti-harassment policy. In particular, sponsors should not use sexualized images, activities, or other material. Booth staff (including volunteers) should not use sexualized clothing/uniforms/costumes, or otherwise create a sexualized environment.

  p If a participant engages in harassing behavior, the conference organisers may take any action they deem appropriate, including warning the offender or expulsion from the conference with no refund.

  p If you are being harassed, notice that someone else is being harassed, or have any other concerns, please contact a member of conference staff immediately. Conference staff can be identified as they&#39;ll be wearing branded t-shirts.

  p Conference staff will be happy to help participants contact hotel/venue security or local law enforcement, provide escorts, or otherwise assist those experiencing harassment to feel safe for the duration of the conference. We value your attendance.

  p We expect participants to follow these rules at conference and workshop venues and conference-related social events.

section.code-of-conduct

  p.m--small
    | Original source and credit: #{ link_to "http://2012.jsconf.us/#/about" } &amp; #{ link_to "The Ada Initiative", "http://geekfeminism.wikia.com/wiki/Conference_anti-harassment/Policy"}

  p.m--small
    | Please help by translating or improving: #{ link_to "https://github.com/leftlogic/confcodeofconduct.com" }

  p.m--small
    | This work is licensed under a #{ link_to "Creative Commons Attribution 3.0 Unported License", "http://creativecommons.org/licenses/by/3.0/deed.en_US", rel: "license" }

app/views/pages/get_there.html.slim
- content_for :title do
  | Get There | GeekCamp.id

section.get-there

    header.header How To Get There

    .get-there__content
      ul.get-there__attendee
        li.get-there__attendee_item If you come before 10.00 WIB, enter via South Lobby (door behind Calvin Klein), use lift to The Hall.
        li.get-there__attendee_item If you come by car before 10.00 WIB, park at P6A, and then use lift to get there.
        li.get-there__attendee_item If you come after 10.00 WIB, go to Senayan City 6th floor, use escalator in front of lift.

    = render 'location'

app/views/pages/home.html.slim
- content_for :title do
  | GeekCamp.id

= render 'jumbotron'
= render 'about'

div.lr_embed( style='position: relative; padding-bottom: 50%; height: 0; overflow: hidden; margin: 2rem 0;' )
  iframe#iframe(
    src='https://lightroom.adobe.com/embed/shares/19ee171f07bb466bb1c3d48aad2ab4e7/slideshow?background_color=%23FBFBFB&color=%23707070'
    frameborder='0'
    style='width:100%; height:100%; position: absolute; top:0; left:0;'
  )

/= render '2017/schedule'
/= render 'location'
/= render '2017/organizers'
/= render '2017/sponsors'
/= render '2017/media_partners'
/= render '2017/communities'
/= render '2017/participate'

app/views/pages/new_cfp.html.slim
- content_for :title do
  | New Talk! | GeekCamp.id

// Would be interesting to try this to make the form more native:
// https://morningstudio.com.au/blog/2013/06/how-to-style-google-forms/

iframe#cfp-form(
  src="https://docs.google.com/forms/d/e/1FAIpQLScWzsCsocMVrM5A4wh7U1I0FFjgCivHBOh2ekdIN0zZrMIuFg/viewform?embedded=true"
  width="640"
  height="1115"
  frameborder="0"
  marginheight="0"
  marginwidth="0"
  allowtransparency="true"
)
  | Loading...

app/views/pages/sponsor.html.slim
- content_for :title do
  | Sponsor! | GeekCamp.id

= render 'jumbotron'

section.sponsor__section

  ul.sponsor__opportunities
    li.sponsor__opportunity
      = link_to image_path("sponsor/branding-opportunities.jpg"), target: '_blank' do
        = image_tag "sponsor/branding-opportunities.jpg", alt: 'Branding Opportunities'
      p Branding Opportunities

    li.sponsor__opportunity
      = link_to image_path("sponsor/engage-engineers.jpg"), target: '_blank' do
        = image_tag "sponsor/engage-engineers.jpg", alt: 'Engage Engineers'
      p Engage Engineers

    li.sponsor__opportunity
      = link_to image_path("sponsor/exhibition-space.jpg"), target: '_blank' do
        = image_tag "sponsor/exhibition-space.jpg", alt: 'Exhibition Space'
      p Exhibition Space


section.sponsor__section

  iframe#sponsor-form(
    src="https://docs.google.com/forms/d/e/1FAIpQLSe3eawU4V59WdoHrJu9HGfYYKgA7CAgw1zVRw6GGaPIl_Hv2w/viewform?embedded=true"
    width="640"
    height="1450"
    frameborder="0"
    marginheight="0"
    marginwidth="0"
  )
    | Loading...

app/views/pages/ticket.html.slim
- content_for :title do
  | Ticket | GeekCamp.id

// Would be interesting to try this to make the form more native:
// https://morningstudio.com.au/blog/2013/06/how-to-style-google-forms/

iframe#ticket-form(
  src="https://docs.google.com/forms/d/e/1FAIpQLSeZ8C0Q8QDT51IVEKUZRzMn3Uugj_GoT0xkIQkaTnvt-y3asA/viewform?embedded=true"
  width="760"
  height="1100"
  frameborder="0"
  marginheight="0"
  marginwidth="0"
  allowtransparency="true"
)
  | Loading...

app/views/pages2015/home.html.slim
- content_for :title do
  | 2015 | GeekCamp.id

= render 'jumbotron'
= render 'speakers'
= render 'schedule'
= render 'organizers'
= render 'sponsors'
= render 'media_partners'
= render 'communities'

app/views/pages2017/_sponsors.html.slim
section.section#sponsors

  header.header Main Sponsors

  .partners
    = link_to 'https://cloud.google.com/?utm_source=geekcamp', target: '_blank', class: 'partner m--main'
      = image_tag 'logo/google-cloud--big.png', class: 'partner__logo m--narrow', alt: 'google cloud'

    = link_to 'https://www.grab.com/?utm_source=geekcamp', target: '_blank', class: 'partner m--main'
      = image_tag 'logo/grab--small.png', class: 'partner__logo', alt: 'grab'

  header.header Additional Sponsors

  .partners
    = link_to 'https://www.akamai.com/?utm_source=geekcamp', target: '_blank', class: 'partner'
      = image_tag 'logo/akamai--small.png', class: 'partner__logo', alt: 'akamai'

    = link_to 'https://www.bbm.com/?utm_source=geekcamp', target: '_blank', class: 'partner'
      = image_tag 'logo/bbm--small.png', class: 'partner__logo', alt: 'bbm'

    = link_to 'https://www.bukalapak.com/?utm_source=geekcamp', target: '_blank', class: 'partner'
      = image_tag 'logo/bukalapak--small.png', class: 'partner__logo', alt: 'bukalapak'

    = link_to 'https://geekhunter.co/?utm_source=geekcamp', target: '_blank', class: 'partner'
      = image_tag 'logo/geekhunter--small.jpg', class: 'partner__logo m--with-background', alt: 'geekhunter'

    = link_to 'https://hacktiv8.com/?utm_source=geekcamp', target: '_blank', class: 'partner'
      = image_tag 'logo/hacktiv8--small.png', class: 'partner__logo m--with-background', alt: 'hacktiv8'

    = link_to 'https://www.jenius.com/?utm_source=geekcamp', target: '_blank', class: 'partner'
      = image_tag 'logo/jenius--small.png', class: 'partner__logo', alt: 'jenius'

    = link_to 'https://www.dewaweb.com/?utm_source=geekcamp', target: '_blank', class: 'partner'
      = image_tag 'logo/dewaweb--small.png', class: 'partner__logo', alt: 'dewaweb'

    = link_to 'https://mokapos.com/?utm_source=geekcamp', target: '_blank', class: 'partner'
      = image_tag 'logo/moka.png', class: 'partner__logo', alt: 'mokapos'

    = link_to 'https://cloudera.com/?utm_source=geekcamp', target: '_blank', class: 'partner'
      = image_tag 'logo/cloudera.png', class: 'partner__logo', alt: 'cloudera'


  /.call-to-sponsor
  /  = link_to "Become a sponsor!", sponsor_path, class: 'button'